# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_user_allpokes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pokee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='poke.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='poke.User')),
            ],
        ),
    ]
