# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allPokes',
        ),
    ]
